runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /picture
  static_dir: picture


- url: /
  script: login.php

- url: /main
  script: main.php

- url: /login
  script: login.php

- url: /register
  script: register.php

- url: /speak
  script: speak.php

- url: /otherCountries
  script: otherCountries.php

- url: /name
  script: name.php

- url: /youtube
  script: youtube.php

- url: /game
  script: game.php

- url: /cook
  script: cook.php

- url: /workout
  script: workout.php

- url: /music
  script: music.php

- url: /selectCountry
  script: selectCountry.php

- url: /translate
  script: translate.php

- url: /texttospeech
  script: textToSpeech.php




skip_files:
- ^(.*/)?.*/assets/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/test/.*$
- ^(.*/)?.*/templates/.*$
- ^(.*/)?.*/node_modules/.*$

- ^(assets/.*)
- ^(build/.*)
- ^(test/.*)
- ^(templates/.*)
- ^(node_modules/.*)

- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

